# This is a basic workflow to help you get started with Actions

name: iOS Fastlane Build & Test

on:
  push:
    branches:
      - development

jobs:
  build_and_test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer

      - name: Install dependencies (Bundler and Fastlane)
        run: |
          sudo gem install bundler
          bundle install || true
          sudo gem install fastlane

      - name: Build app with Fastlane
        run: fastlane build_only

      - name: Run tests with Fastlane
        run: fastlane tests
